### ISSUE TITLE
Show information about performed refactorings in deleted/added files

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/RefactorInsight#102]
Currently, plugin doesn't show the toggle in code diff in case of removed/added files.
For example, if a method was moved to a new file, the plugin doesn't show any information about it in code diff.

Test for Move Method, Extract Method, Extract Class.

**Comment by anchouls** [comment]
#103

**Comment by onewhl** [comment]
@anchouls please check if it works fro [Arend](https://github.com/JetBrains/Arend) project, commit c0ff902179c002d0c2bc57f809f166946e65e8d2.
It seems it doesn't show a toggle in new file for Move and Rename Class refactoring.
