### ISSUE TITLE
Change Variable Type: diff doesn't highlight changed type

### ISSUE THREAD

**Issue by dimonchik0036** [JetBrains-Research/RefactorInsight#119]
Probably entrire `Collection collection = myCache.get(key)` and `Collection<V> collection = myCache.get(key)` should be highlighted
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/22503910/223795922-d70045bb-b29b-4b52-80e9-1d7d743e73a9.png">

**Comment by onewhl** [comment]
@dimonchik0036 thank you for reporting! @anchouls could you take a look at it, please?

**Comment by tsantalis** [comment]
@onewhl @anchouls 
Please look my comment at https://github.com/JetBrains-Research/RefactorInsight/wiki/Visualisation-of-refactorings#change-variableparameterattribute-type

**Comment by onewhl** [comment]
@tsantalis thank you for investigating, I applied the changes that you suggested to fix the issue!
@dimonchik0036 I've just fixed the issue, the fix will come in the next plugin release.

**Comment by tsantalis** [comment]
@onewhl 
The same change should be done for Change Attribute Type, if it is not already using `getType()`.

**Comment by onewhl** [comment]
@tsantalis , it already uses `getType()`.
