### ISSUE TITLE
Excessive memory consumption by the plugin

### ISSUE THREAD

**Issue by juliabeliaeva** [JetBrains-Research/refactorinsight#36]
![image](https://user-images.githubusercontent.com/58706/88123146-f1e35680-cbd2-11ea-9f1c-5e73339f7565.png)
![image](https://user-images.githubusercontent.com/58706/88122838-42a67f80-cbd2-11ea-945f-b290a6bc64bb.png)

It looks like the plugin has started 8 threads to process commits, and each of the threads has loaded a big `PackFile`.

```
IntelliJ IDEA 2020.1.3 (Community Edition)
Build #IC-201.8538.31, built on July 7, 2020
Runtime version: 11.0.7+10-b765.64 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 2981M
Cores: 8
```

Plugin version `2020.1-1.1`

**Comment by bbrockbernd** [comment]
@juliabeliaeva Thank you! The memory usage is indeed dependent on the amount of threads (for now). We are trying to make changes to the RefactoringMiner API so the threads can share jGit instances. 

Until then you could decrease the amount of threads used in the settings of RefactorInsight: Settings -> Tools -> RefactorInsight -> Number of threads to use for mining

**Comment by juliabeliaeva** [comment]
@bbrockbernd thanks for the tip, with only one thread memory consumption becomes tolerable.
