### ISSUE TITLE
All differences ignored with "Ignore whitespaces and empty lines" when opened from Git window

### ISSUE THREAD

**Issue by sim642** [JetBrains-Research/refactorinsight#46]
When I double click on a file with a refactoring in the Git window, it shows me an empty diff and the message "Differences ignored". This seems to be because I have chosen "Ignore whitespaces and empty lines". If I change that to anything else, the refactoring differences actually show. For whatever reason the diff window decides to ignore renaming etc even though it's not just whitespace or empty line change.

With "Ignore whitespaces and empty lines":
![Screenshot_2020-07-31_12-38-22](https://user-images.githubusercontent.com/378740/89022520-d989df00-d32a-11ea-845e-94f3c5ce7b46.png)

With "Do not ignore":
![Screenshot_2020-07-31_12-38-29](https://user-images.githubusercontent.com/378740/89022536-dee72980-d32a-11ea-989f-40359762bb36.png)

---

Maybe related observation: a normal (non-refactoring) diff for that commit shows the corresponding commit hashes in the diff window, but the refactoring diff only shows the file paths (same on both sides):
![Screenshot_2020-07-31_12-41-00](https://user-images.githubusercontent.com/378740/89022788-3b4a4900-d32b-11ea-8d21-ed297fcbd7ef.png)

Comparing the "Highlight words" in this normal diff to the one above, it also looks like "Highlight words" works differently in a refactoring diff window. Also, code highlighting is different and lacking some colors.

**Comment by onewhl** [comment]
Hi, @sim642!
Thank you for letting us know about the problem and providing a detailed description!
Please, clarify the version of the used IDEA and the version of the plugin.

**Comment by sim642** [comment]
* IntelliJ version: IntelliJ IDEA 2020.2 (Ultimate Edition) Build #IU-202.6397.94, built on July 27, 2020
* Plugin version: 2020.2-1.0
