### ISSUE TITLE
"Show Refactoring Labels" should be disabled when there is no log tab visible

### ISSUE THREAD

**Issue by juliabeliaeva** [JetBrains-Research/RefactorInsight#60]
Currently the action is not disabled, but just does nothing:
![image](https://user-images.githubusercontent.com/58706/91567080-38a03b00-e94d-11ea-80ac-6aef00244221.png)

To fix this, `AnAction#update` should be overriden. See, for example, [ToggleRefactoringViewAction#update](https://github.com/juliabeliaeva/refactorinsight/blob/b00b1bec36ef5b87fc41bf71569b4f75561c2ab3/src/main/java/org/jetbrains/research/refactorinsight/actions/ToggleRefactoringViewAction.java#L36).

**Comment by onewhl** [comment]
Disabled actions when there is no log tab visible
![disabled-labels](https://user-images.githubusercontent.com/10652414/92534117-a6e1d900-f23c-11ea-90d8-fe404d1d8269.png)
