### ISSUE TITLE
Refactoring icons are not displayed in the table.

### ISSUE THREAD

**Issue by juliabeliaeva** [JetBrains-Research/RefactorInsight#64]
The icons are not shown because [`table.setDefaultRenderer(String.class, new VcsTableRefactoringRenderer(p))`](https://github.com/JetBrains-Research/RefactorInsight/blob/797d2c38e697a11e0102b971c827dec342897896/src/main/java/org/jetbrains/research/refactorinsight/ui/windows/GitWindow.java#L65) call does not work in IntelliJ 2020.3.

On the following screenshot the toggle is set, and the selected commit has refactorings, but the icon is not visible:
![image](https://user-images.githubusercontent.com/58706/104827980-6b53bd00-5875-11eb-85f5-901b4f70ca83.png)

Version 1.0.42

**Comment by juliabeliaeva** [comment]
I can send a PR with the feature reimplemented with the new [`VcsLogCustomColumn`](https://github.com/JetBrains/intellij-community/blob/master/platform/vcs-log/impl/src/com/intellij/vcs/log/ui/table/column/VcsLogCustomColumn.kt) api. The downside of this api is that custom columns are enabled by default, which is different from the current implementation. This could be surprising to the users, so I'm not sure if this is the right change to make.

Here is the screenshot of log tab with the new column:
![image](https://user-images.githubusercontent.com/58706/104828114-e1a4ef00-5876-11eb-8967-977b960b57f3.png)
The new api creates actions to enable columns in the "Show Columns" menu, so the custom action will be no longer needed (not sure if "Detected Refactorings" is good column name, suggestions are welcome):
![image](https://user-images.githubusercontent.com/58706/104828152-33e61000-5877-11eb-9809-177cb5dc30e4.png)

**Comment by onewhl** [comment]
@juliabeliaeva, it looks good, thank you! To be clear, we will add the information about this feature with a screenshot to README.

**Comment by juliabeliaeva** [comment]
> The downside of this api is that custom columns are enabled by default, which is different from the current implementation. This could be surprising to the users, so I'm not sure if this is the right change to make.

@onewhl, Just to clarify, do you think it's ok to display the refactoring labels by default?

**Comment by onewhl** [comment]
@juliabeliaeva I see, that indeed might be confusing for the users. Is there no other way to add the column and show it only if the user wants to see it?

**Comment by juliabeliaeva** [comment]
> Is there no other way to add the column and show it only if the user wants to see it?

I don't know any. We can add api for it in the next version (2021.1).

**Comment by juliabeliaeva** [comment]
Api was added to 2021.1: https://github.com/JetBrains/intellij-community/commit/aabbc19ec5a1c25feaa927932045d8f87d6f8ec5

**Comment by onewhl** [comment]
@juliabeliaeva that's great, thank you!
